### ISSUE TITLE
Cannot require tech.ml after installing

### ISSUE THREAD

**Issue by lccambiaghi** [tech-ascent/tech.ml-base#10]
Hi, I am probably missing something obvious here but:
```
clj -Sdeps '{:deps {techascent/tech.ml {:mvn/version "3.00"}}}'
Clojure 1.10.1

user=> (require '[tech.ml :as ml])
Syntax error (FileNotFoundException) compiling at (tech/ml/protocols/system.clj:1:1).
Could not locate tech/v2/datatype/casting__init.class, tech/v2/datatype/casting.clj or tech/v2/datatype/casting.cljc on classpath.
```

Should there be more dependencies alongside `tech.ml`? Thank you!

**Comment by cnuernber** [comment]
Yes but I am conflicted.  I removed tech.ml.dataset from tech.ml because I was doing too many 'point' release where the only thing that changed was some underlying library.

**Comment by cnuernber** [comment]
Closing this for now :-).
