### ISSUE TITLE
add sparse data support to xgboost

### ISSUE THREAD

**Issue by behrica** [tech-ascent/tech.ml-base#19]
This should be rather simple, I believe.
The DMatrix class has one specific constructor for "sparse" data.

DMatrix(long[] headers,
               int[] indices,
               float[] data,
               DMatrix.SparseType st,
               int shapeParam)
               
So hopefully only a few lines need to be changed in Xboost.clj to add support for sparse data.

I can give this an initial go.

**Comment by cnuernber** [comment]
Very cool.  So we would take a sparse column and have xgboost work from one column as opposed to a column per feature?

**Comment by behrica** [comment]
yes. I have done this in the other cases as well.

**Comment by cnuernber** [comment]
Sounds good to me.  Solid approach in a lot of ways.  Simple and easy to optimize.
