### ISSUE TITLE
grid-search should try/catch calls to train/predict

### ISSUE THREAD

**Issue by behrica** [tech-ascent/tech.ml-base#33]
as a grid-search can run a long time, and any model has a "certain risk" to fail  with an exception on a certain parameter combination,
I propose to try/catch calls  to train/predict  in case of grid search and just log (and ignore basically the failing options)

This should be done only for function train-auto-gridsearch

**Comment by cnuernber** [comment]
Agreed completely

**Comment by behrica** [comment]
will do PR soon.
