### ISSUE TITLE
explain of ordinary-least-square returns wrong intercept

### ISSUE THREAD

**Issue by behrica** [tech-ascent/tech.ml-base#44]
For OLS for some reason the intercept is not retrieved via `.intercept`,
but it is the first coefficient.

The toString method in 
https://github.com/haifengl/smile/blob/5ec63ae4c1e2b210131328054b6bf1e29bc30854/core/src/main/java/smile/regression/LinearModel.java#L454

makes this distinction.

In ols we have 2 predictors, were one is called "intercept".

I am not sure, if this is a bug in `LinearModel.java`.
The OLS internals looks like this in my case:

```
  "F" = 1434.7560472822506
  "RSS" = 51.208299656758086
  "RSquared" = 0.9676278507931366
  "V" = 2 x 2
          0.0925      -0.0139
         -0.0139       0.0027

  "adjustedRSquared" = 0.9669534310179937
  "b" = 0.0
  "df" = 48
  "error" = 1.0328792650559213
  "fittedValues" = double[] { 8.810672771373527, 3.407132674340155, 4.706922652953522, 4.537351720910456, 7.404580114815568 ... }
  "formula" = y ~ x
  "p" = 2
  "predictors" = java.lang.String[] { "Intercept", "x" }
  "pvalue" = 2.041879706207946E-37
  "residuals" = double[] { 0.2926866000501942, 0.5782395113669372, -0.5589799907144473, -0.11086940107860777, -0.5332625493744363 ... }
  "schema" = [x: double]
  "ttest" = [D[] { double[] { -5.0598809088126115, 0.31418487655094346, -16.104788251932863, 5.50106185935235E-21 }, double[] { 2.015121338306577, 0.05320006585196511, 37.878173758541365, 2.041879706207945E-37 } }
  "w" = double[] { -5.0598809088126115, 2.015121338306577 }

Static fields:
  "logger" = Logger[smile.regression.LinearModel]
  "serialVersionUID" = 2
```
The correct intercept would be -5.0598809088126115 and the coefficient of for x should be 2.015121338306577 .
(so first and second element of `w`)

but `techml/explain` returns:

```
  :bias = 0.0
  :coefficients = ( [ :x -5.0598809088126115 ] )
```
(so `b` and first element of `w`)

The model does the correct predictions, only the explain seems to be wrong.

Eventually this is related to:

https://github.com/haifengl/smile/issues/599
which resulted in this line to adapt the prediction:
https://github.com/techascent/tech.ml/blob/f9384025e7ce6f26bc0334be615f53feeaf2117a/src/tech/v3/libs/smile/regression.clj#L87

**Comment by cnuernber** [comment]
Yep, I was hoping those models were standardized but of course they can have slight differences.
