### ISSUE TITLE
easier access to undelying model object

### ISSUE THREAD

**Issue by behrica** [tech-ascent/tech.ml-base#45]
It should be easier to get to the underlying model object instance.
Currently the thaw-model function requires the thaw-fn to be given

```clojure
(def trained-old (ml/train .....

 (def thaw-fn
  (ml/options->model-def (:options trained-ols)))
(ml/thaw-model trained-ols thaw-fn)
```

**Comment by cnuernber** [comment]
I agree with this entirely.
I think that function should have a single-arity pathway that assoc's thawed-model into the return value of train.
