### ISSUE TITLE
add data pre-processor PolynomialFeatures

### ISSUE THREAD

**Issue by behrica** [tech-ascent/tech.ml-base#46]
see [sklearn.preprocessing.PolynomialFeatures](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html).

**Comment by cnuernber** [comment]
Cool function.  Seems like it would potentially go into dataset.

**Comment by behrica** [comment]
Yes, agree.
Here is not the place for it.
I will open in tablecloth
