### ISSUE TITLE
Not able to run: No implementation of method: :columns of protocol: #'tech.v3.protocols.dataset/PColumnarDataset found for class: clojure.lang.PersistentVector

### ISSUE THREAD

**Issue by lucasemmoreira** [tech-ascent/tech.ml-base#49]
Hi there!

Awesome lib! I am playing around with it and something strange happened.

I am coding on emacs with cider and I used the lib normally. I was able to compile and run within emacs.

But when I tried to use leiningen to run with 

`lein run`

the error as above was shown
`No implementation of method:columns of protocol: #'tech.v3.protocols.dataset/PColumnarDataset found for class: clojure.lang.PersistentVector`

My code is the same as the example in the readme... Not sure what I am doing wrong. I tried with the beta 14 and 12.

here is the report generated
https://gist.github.com/lucasemmoreira/c19d574cdae20ca9a309e100649eee64

**Comment by cnuernber** [comment]
Hey, great to hear, thank you!

Do you have a link to the code? It appears append-ds is passing in a persistent vector into concat as opposed to a dataset.

**Comment by lucasemmoreira** [comment]
There you go:
https://github.com/lucasemmoreira/techml-test

**Comment by cnuernber** [comment]
```console

chrisn@chrisn-lt-01:~/dev/issues/techml-test$ lein run
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/chrisn/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/chrisn/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
0.1528326049778196
Hello, World!
```

After removing the clj-http require.

**Comment by lucasemmoreira** [comment]
hmmm, thats interesting! thank you very much!
For me take this as an oportunity to learn a bit more: could you point me to what kind of problem I am looking at? Because the error I get does not seem to mention a library conflict.

Thank you again!

**Comment by cnuernber** [comment]
It is not a library conflict IMO.  You will get the same error if you do `(ds/columns [])`.

**Comment by lucasemmoreira** [comment]
@cnuernber It was a mistake on my part (as usually are from users hehehe)
I had a problem, tried to replicate using the example from the readme and because it was showing the same error on the console I assumed it was the same problem. 

As you mentioned here, my original problem was the use of the function concat. I appreciate your time helping me. I will be closing this.

> Hey, great to hear, thank you!
> 
> Do you have a link to the code? It appears append-ds is passing in a persistent vector into concat as opposed to a dataset.
